FROM 3.12.3-slim-bullseye
RUN echo 'Acquire::http::Proxy "http://proxies.labs:3142/apt-cacher/";' > /etc/apt/apt.conf.d/01proxy
RUN apt-get update && apt-get install --no-install-recommends -y make python3 python3-pip python3-distutils

ADD requirements.txt /tmp/requirements.txt
RUN cd /tmp && python3 -m venv venv && venv/bin/pip install -rrequirements.txt
RUN mkdir -p /usr/src 

COPY . /usr/src/app/
WORKDIR /usr/src/app/

RUN ln -s /tmp/venv /usr/src/app/venv
ENTRYPOINT /bin/bash
RUN make all
