FROM python:3.8-slim-buster
RUN echo 'Acquire::http::Proxy "http://proxies.labs:3142/apt-cacher/";' > /etc/apt/apt.conf.d/01proxy
RUN apt-get update && apt-get install --no-install-recommends -y git openssh-client ca-certificates python2 make g++ 

ADD setup.py /tmp/setup.py
RUN cd /tmp && python3.8 -m venv venv && venv/bin/pip install -e . 
RUN mkdir -p /usr/src 

COPY . /usr/src/app/
WORKDIR /usr/src/app/

RUN ln -s /tmp/venv /usr/src/app/venv
ENTRYPOINT /bin/bash
RUN make all
