[development]
LOG_PATH="/tmp/logs"
LOG_URL="http://ci.labs/logs/{logfile}"
CLONE_PATH="/tmp/repos"
TELEGRAM_BOT_KEY="set me up!"
S3_PROFILE='ci'
S3_ENDPOINT='http://localhost:9000'
DOCKERFILES.NPM="Dockerfile-npm"
DOCKERFILES.PYTHON="Dockerfile-python"
REST_DEPLOYER_URL='http://localhost:8080/sync/deploy/{repo}/{ref}'
REST_DEPLOYER_SECRET='some secret'
WEBSERVER_PORT=8123
WORKER_QUEUE_NAME='ci'
WORKER_COUNT=2
KILL_WORKERS_ON_SIGNAL=false

  [[development.REPOS]]
  Name="Test Repo"
  GitUrl="Some URL"
  Bucket="testrepo"
  TelegramChatId=1234
  Notifier="Telegram"
  Deployer="REST"
  REST_DEPLOYER_URL='http://localhost:8080/sync/deploy/{repo}/{ref}'
