[development]
CLONE_PATH="/tmp/"
TELEGRAM_BOT_KEY="set me up!"
DOCKERFILES.NPM="Dockerfile-npm"
DOCKERFILES.PYTHON="Dockerfile-python"

  [[development.REPOS]]
  Name="Test Repo"
  GitUrl="Some URL"
  Bucket="testrepo"
  TelegramChatId=1234
  AnsibleDeployer="http://set.me.up"
